include_guard()

set(CMAKE_SYSTEM_NAME "kernel-486")
set(CMAKE_SYSTEM_VERSION 1)

set(CMAKE_CROSSCOMPILING TRUE)

# Shared libraries are not supported at all
set_property(GLOBAL PROPERTY TARGET_SUPPORTS_SHARED_LIBS FALSE)

set(CMAKE_SYSTEM_PROCESSOR "486")

if (CMAKE_TOOLCHAIN_FILE)
endif()

set(CMAKE_C_COMPILER "i486-elf-gcc" CACHE FILEPATH "")
set(CMAKE_CXX_COMPILER "i486-elf-g++" CACHE FILEPATH "")
set(CMAKE_LINKER "i486-elf-ld" CACHE FILEPATH "")
set(CMAKE_AR "i486-elf-ar" CACHE FILEPATH "")
set(CMAKE_C_COMPILER_AR "i486-elf-ar" CACHE FILEPATH "")

set(CMAKE_C_COMPILER_ID_RUN TRUE)
set(CMAKE_C_COMPILER_FORCED TRUE)
set(CMAKE_C_COMPILER_WORKS TRUE)
set(CMAKE_C_COMPILER_ID GNU)
set(CMAKE_C_COMPILER_FRONTEND_VARIANT "")
set(CMAKE_C_STANDARD_COMPUTED_DEFAULT 20)

set(CMAKE_CXX_COMPILER_ID_RUN TRUE)
set(CMAKE_CXX_COMPILER_FORCED TRUE)
set(CMAKE_CXX_COMPILER_WORKS TRUE)
set(CMAKE_CXX_COMPILER_ID GNU)
set(CMAKE_CXX_COMPILER_FRONTEND_VARIANT "")
set(CMAKE_CXX_STANDARD_COMPUTED_DEFAULT 20)

set(KERNEL_C_FLAGS "-ffreestanding")
set(CMAKE_C_FLAGS_DEBUG_INIT " ${KERNEL_C_FLAGS} -g ")
set(CMAKE_C_FLAGS_MINSIZEREL_INIT " ${KERNEL_C_FLAGS} -Os ")
set(CMAKE_C_FLAGS_RELEASE_INIT " ${KERNEL_C_FLAGS} -O2 ")
set(CMAKE_C_FLAGS_RELWITHDEBINFO_INIT " ${KERNEL_C_FLAGS} -O2 -g ")

set(KERNEL_CXX_FLAGS "-ffreestanding")
set(CMAKE_CXX_FLAGS_DEBUG_INIT " ${KERNEL_C_FLAGS} -g ")
set(CMAKE_CXX_FLAGS_MINSIZEREL_INIT " ${KERNEL_C_FLAGS} -Os ")
set(CMAKE_CXX_FLAGS_RELEASE_INIT " ${KERNEL_C_FLAGS} -O2 ")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO_INIT " ${KERNEL_C_FLAGS} -O2 -g ")

set(KERNEL_LINK_FLAGS "--oformat binary")
string(APPEND CMAKE_EXE_LINKER_FLAGS_DEBUG_INIT " ${KERNEL_LINK_FLAGS} ")
string(APPEND CMAKE_EXE_LINKER_FLAGS_MINSIZEREL_INIT " ${KERNEL_LINK_FLAGS} ")
string(APPEND CMAKE_EXE_LINKER_FLAGS_RELEASE_INIT " ${KERNEL_LINK_FLAGS} ")
string(APPEND CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO_INIT " ${KERNEL_LINK_FLAGS} ")

set(CMAKE_EXECUTABLE_SUFFIX ".bin")

set(CMAKE_SKIP_COMPATIBILITY_TESTS 1)
set(CMAKE_SIZEOF_CHAR 1)
set(CMAKE_SIZEOF_UNSIGNED_SHORT 2)
set(CMAKE_SIZEOF_SHORT 2)
set(CMAKE_SIZEOF_INT 4)
set(CMAKE_SIZEOF_UNSIGNED_LONG 4)
set(CMAKE_SIZEOF_UNSIGNED_INT 4)
set(CMAKE_SIZEOF_LONG 4)
set(CMAKE_SIZEOF_VOID_P 4)
set(CMAKE_SIZEOF_FLOAT 4)
set(CMAKE_SIZEOF_DOUBLE 8)
set(CMAKE_C_SIZEOF_DATA_PTR 4)
set(CMAKE_HAVE_LIMITS_H 0)
set(CMAKE_HAVE_UNISTD_H 0)
set(CMAKE_HAVE_PTHREAD_H 0)
set(CMAKE_HAVE_SYS_PRCTL_H 0)
set(CMAKE_WORDS_BIGENDIAN 0)
set(CMAKE_DL_LIBS)

set(CMAKE_C_COMPILE_OBJECT
  "<CMAKE_C_COMPILER> <INCLUDES> <DEFINES> <FLAGS> -c <SOURCE> -o <OBJECT>")

set(CMAKE_CXX_COMPILE_OBJECT
  "<CMAKE_CXX_COMPILER> <INCLUDES> <DEFINES> <FLAGS> -c <SOURCE> -o <OBJECT>")

set(CMAKE_C_LINK_EXECUTABLE
  "<CMAKE_LINKER> -o <TARGET> <LINK_FLAGS> <LINK_LIBRARIES> <OBJECTS>")
